---
tap_install:
  values:
    profile: full

    shared:
      ingress_domain: workshop.corby.page
      image_registry:
        project_path: gcr.io/fe-cpage/tap
        username: _json_key

      kubernetes_version: 1.25.9

    ceip_policy_disclosed: true

    # These packages will be deprecated in future versions of TAP, so we will exclude them to free up space on the cluster
    excluded_packages:
      - learningcenter.tanzu.vmware.com
      - workshops.learningcenter.tanzu.vmware.com
      - eventing.tanzu.vmware.com
